name: Single Cypress Tests

on:
  schedule:
    - cron: "*/5 * * * *"

env:
  VITE_API_URL: http://localhost:3001
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  component-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: someFeature
      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: npm run build
      - name: Run CT Tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:ct:ci
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: someFeature
      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: npm run build
      - name: Run E2E Tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ci
          command: npm run test:e2e:ci
          wait-on: 'http://localhost:3000, http://localhost:3001/heroes'